repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: ^docs/
    -   id: end-of-file-fixer
        exclude: ^docs/
    -   id: trailing-whitespace
        exclude: ^docs/

- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.3
  hooks:
    - id: autoflake
      args: ['--in-place', '--expand-star-imports', '--ignore-init-module-imports', '--remove-all-unused-imports']
      exclude: ^docs/

-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--line-length=100]
        exclude: ^docs/

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -  id: isort
       exclude: ^docs/
